data:
  image_path: '/mnt/data/psemchyshyn/top-detection/mlc_training_data/images'
  label_path: '/mnt/data/psemchyshyn/top-detection/mlc_training_data/ground_truth_files'
  test_data_path: '/mnt/data/psemchyshyn/top-detection/mlc_test_images'
  image_w: 512
  image_h: 512
  original_image_size: 512
  train_size: 0.8
  batch_size: 4
  train_augs: 'none'
  val_augs: 'none'
  tta: false

training: 
  lr: 0.00001
  epochs: 12
  set_height_to: 9.0
  cache_dir: '/mnt/data/psemchyshyn/top-detection/cache'
  save_logs_dir: 'logs'
  save_weights_dir: '/mnt/data/psemchyshyn/top-detection/checkpoints'
  save_results_dir: 'test_results'
  save_temp_val_results_dir: '/mnt/data/psemchyshyn/top-detection/val/temp_val_results'
  save_temp_train_results_dir: '/mnt/data/psemchyshyn/top-detection/train/temp_train_results'
  train_labels_dir: '/mnt/data/psemchyshyn/top-detection/train/labels'
  val_labels_dir: '/mnt/data/psemchyshyn/top-detection/val/labels'
  train_labels_dir_gt: '/mnt/data/psemchyshyn/top-detection/train/labels_temp'
  val_labels_dir_gt: '/mnt/data/psemchyshyn/top-detection/val/labels_temp'
  wandb_project_name: 'top-detection'
  wandb_run_name: 'sam_base_augs-train_none-val_none_loss-jaccard_height9_tta-false_512-bs4'
  
prediction:
  mask_threshold: 0.5
  max_vertices: 8
  epsilon: 0.001
